# !-----------------------------------------------------------------------------------------------!
#                       Welcome to the main configuration of OneBlock
# !-----------------------------------------------------------------------------------------------!
# -------------------------------------------------------------------------------------------------
# The prefix used in front of most chat or console messages. You can manually use it with
# {plugin_prefix} variable anywhere.
# -------------------------------------------------------------------------------------------------
Prefix: '&7&l[&x&0&0&A&B&5&2&lOn&x&0&F&C&0&6&B&leB&x&1&D&D&5&8&5&llo&x&2&C&E&A&9&E&lck&7&l]&f'

# -------------------------------------------------------------------------------------------------
# What language should we use for messages? If it exists, the language file will be copied
# to your messages/ folder where you can edit it.
# -------------------------------------------------------------------------------------------------
locale: en

OneBlock:
  Size: 20 # Size for the OneBlock island in Chunks (in every direction) total chunks would be Size * Size + 1
  LootPool:
    0:
      - 'This is level 0'
      - 'GRASS_BLOCK'
      - 'DIRT'
      - 'COARSE_DIRT'
      - 'OAK_LEAVES'
    1:
      - 'This is level 1'
      - 'OAK_LOG'
      - 'PODZOL'
    2:
      - 'This is level 2'
      - 'BIRCH_LOG'
      - 'OAK_LOG'
      - 'OAK_LEAVES'
      - 'SHEEP'
      - 'COW'
      - 'PIG'
      - 'CHICKEN'
      - 'ZOMBIE'
    3:
      - 'This is level 3'
      - 'STONE'
      - 'COBBLESTONE'
      - 'COAL_ORE'
      - 'GRAVEL'
      - 'SKELETON'
    4:
      - 'This is level 4'
      - 'GRANITE'
      - 'DIORITE'
      - 'ANDESITE'
    5:
      - 'This is level 5'
      - 'SAND'
      - 'SANDSTONE'
      - 'CACTUS'
    6:
      - 'This is level 6'
      - 'IRON_ORE'
      - 'COARSE_DIRT'
      - 'COPPER_ORE'
      - 'DEEPSLATE_COPPER_ORE'
      - 'CREEPER'
    7:
      - 'This is level 7'
      - 'MOSSY_COBBLESTONE'
      - 'WHITE_TERRACOTTA'
      - 'ORANGE_TERRACOTTA'
      - 'YELLOW_TERRACOTTA'
      - 'HORSE'
      - 'MULE'
      - 'DONKEY'
    8:
      - 'This is level 8'
      - 'SPRUCE_LOG'
      - 'DARK_OAK_LOG'
      - 'SPRUCE_LEAVES'
    9:
      - 'This is level 9'
      - 'STONE'
      - 'COAL_ORE'
      - 'GOLD_ORE'
      - 'LAPIS_ORE'
    10:
      - 'This is level 10'
      - 'IRON_ORE'
      - 'INFESTED_STONE'
      - 'SNOW_BLOCK'
      - 'PACKED_ICE'
    11:
      - 'This is level 11'
      - 'CLAY'
      - 'WHITE_CONCRETE'
      - 'RED_SAND'
      - 'RED_SANDSTONE'
      - 'VILLAGER'
    12:
      - 'This is level 12'
      - 'ACACIA_LOG'
      - 'ACACIA_LEAVES'
      - 'MUSHROOM_STEM'
      - 'BROWN_MUSHROOM_BLOCK'
      - 'RED_MUSHROOM_BLOCK'
      - 'MUSHROOM_COW'
    13:
      - 'This is level 13'
      - 'PRISMARINE_BRICKS'
      - 'DARK_PRISMARINE'
      - 'SEA_LANTERN'
      - 'GUARDIAN'
      - 'ELDER_GUARDIAN'
    14:
      - 'This is level 14'
      - 'DIAMOND_ORE'
      - 'EMERALD_ORE'
      - 'CHISELED_SANDSTONE'
    15:
      - 'This is level 15'
      - 'MANGROVE_LEAVES'
      - 'MANGROVE_LOG'
      - 'MANGROVE_PLANKS'
      - 'MUDDY_MANGROVE_ROOTS'
      - 'STRIPPED_MANGROVE_LOG'
      - 'BEE_NEST'
      - 'MUD'
      - 'CLAY'
    16:
      - 'This is level 16'
      - 'CUT_SANDSTONE'
      - 'OBSIDIAN'
    17:
      - 'This is level 17'
      - 'NETHERRACK'
      - 'GLOWSTONE'
      - 'SOUL_SAND'
      - 'PILLAGER'
      - 'ZOMBIFIED_PIGLIN'
    18:
      - 'This is level 18'
      - 'SCULK'
      - 'SCULK_SENSOR'
      - 'SCULK_CATALYST'
      - 'SCULK_SHRIEKER'
      - 'WITHER_SKELETON'
      - 'BLAZE'
      - 'ZOGLIN'
      - 'STRIDER'
    19:
      - 'This is level 19'
      - 'CHISELED_STONE_BRICKS'
      - 'NETHER_BRICKS'
      - 'GREEN_TERRACOTTA'
      - 'PINK_TERRACOTTA'
      - 'NETHER_QUARTZ_ORE'
      - 'BLACK_TERRACOTTA'
      - 'PIGLIN'
      - 'HOGLIN'
    20:
      - 'This is level 20'
      - 'NETHER_BRICKS'
      - 'NETHERRACK'
      - 'NETHER_QUARTZ_ORE'
    21:
      - 'This is level 21'
      - 'PRISMARINE'
      - 'CRIMSON_NYLIUM'
      - 'WARPED_NYLIUM'
      - 'AMETHYST_BLOCK'
      - 'DIAMOND_BLOCK'
    22:
      - 'This is level 22'
      - 'NETHERRACK'
      - 'CRIMSON_STEM'
    23:
      - 'This is level 23'
      - 'WARPED_STEM'
      - 'OXIDIZED_COPPER'
      - 'NETHER_GOLD_ORE'
    24:
      - 'This is level 24'
      - 'DEEPSLATE'
      - 'COBBLED_DEEPSLATE'
      - 'POLISHED_DEEPSLATE'
      - 'DEEPSLATE_BRICKS'
      - 'DEEPSLATE_TILES'
      - 'CHISELED_DEEPSLATE'
      - 'DEEPSLATE_BRICKS'
      - 'OAK_SLAB'
      - 'GRAY_WOOL'
      - 'SCULK_SENSOR'
      - 'REDSTONE_LAMP'
      - 'SOUL_SAND'
      - 'FURNACE'
      - 'LECTERN'
      - 'REDSTONE_BLOCK'
      - 'TARGET'
    25:
      - 'This is level 25'
      - 'CRIMSON_HYPHAE'
      - 'WARPED_HYPHAE'
      - 'CRACKED_NETHER_BRICKS'
    26:
      - 'This is level 26'
      - 'SHROOMLIGHT'
      - 'CRYING_OBSIDIAN'
      - 'BLACKSTONE'
      - 'DEEPSLATE_BRICKS'
      - 'CRACKED_DEEPSLATE_BRICKS'
    27:
      - 'This is level 27'
      - 'NETHERITE_BLOCK'
      - 'ANCIENT_DEBRIS'
      - 'POLISHED_BLACKSTONE'
    28:
      - 'This is level 28'
      - 'END_STONE'
      - 'CUT_SANDSTONE'
      - 'OBSIDIAN'
