# !-----------------------------------------------------------------------------------------------!
#                       Welcome to the main configuration of ${projectName}
# !-----------------------------------------------------------------------------------------------!
# -------------------------------------------------------------------------------------------------
# The prefix used in front of most chat or console messages. You can manually use it with
# {plugin_prefix} variable anywhere.
# -------------------------------------------------------------------------------------------------
Prefix: "&8&l[&x&0&0&A&B&5&2&lOn&x&0&F&C&0&6&B&leB&x&1&D&D&5&8&5&llo&x&2&C&E&A&9&E&lck&7]&f"

# -------------------------------------------------------------------------------------------------
# What language should we use for messages? If it exists, the language file will be copied
# to your messages/ folder where you can edit it.
# -------------------------------------------------------------------------------------------------
locale: en

